name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.4.2
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/typicalcoder/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  dio: ^5.4.0
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.27.7

  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  package_info_plus: ^5.0.1
  open_filex:
    git:
      url: https://github.com/ishaquehassan/open_filex.git
  sensors_plus: ^4.0.2
  share_plus: ^7.2.2
  chopper: ^7.1.1
  collection: ^1.18.0
  url_launcher: ^6.2.4

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: AlicePlugin
      ios:
        pluginClass: AlicePlugin
      macos:
        pluginClass: AlicePlugin
